# GitHub Continuous Deployment

on:
  push:
    branches:
      - master
    tags:
      - "**"

name: "Continuous Deployment"

jobs:
  build:
    name: "Build and deploy"

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: sambacha/brownie-ci-docker

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build Docker image"
        run: $(which docker) build --tag ${DOCKER_IMAGE}:latest .

      - name: "Docker Login"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: echo "${{ secrets.CR_PAT }}" | $(which docker) login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Push Docker image (latest)"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: $(which docker) push ${DOCKER_IMAGE}:latest

      - name: "Tag Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: $(which docker) tag ${DOCKER_IMAGE} ${DOCKER_IMAGE}:$(bash ./bin/tag-name.sh ${GITHUB_REF})

      - name: "Push Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: $(which docker) push ${DOCKER_IMAGE}:$(bash ./bin/tag-name.sh ${GITHUB_REF})

      - name: "Docker Logout"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: $(which docker) logout
