name: dockerimage

on: push

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: brownie-ci

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  ghr_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build ${IMAGE_NAME} image
        run: IMAGE_NAME=brownie-ci docker build ./ --file ./Dockerfile --tag brownie-ci

      - name: Log into GitHub Container Registry
      # Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push ${IMAGE_NAME} image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/brownie-ci

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

           echo IMAGE_ID=$IMAGE_ID
           echo VERSION=$VERSION
          
          docker tag docker.pkg.github.com/sambacha/brownie-ci-docker/brownie-ci:1.0.0
          docker push docker.pkg.github.com/sambacha/brownie-ci-docker/brownie-ci:1.0.0
